name: numbers_to_text
description: convert numbers into their textual representation in both Arabic and English.
version: 0.1.2
repository: https://github.com/masreplay/numbers_to_text

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  intl: ^0.18.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
